/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */
import { Validators, FormControl, FormGroup, FormArray, ValidatorFn } from '@angular/forms';
import { minValueValidator, maxValueValidator, enumValidator } from './validators';
import { BaseModel } from './base-model';
import { SubTypeFactory } from './sub-type-factory';


export interface IGetPrice_inputs {
    contractAddress?: string;
    data?: string;
}


export class GetPrice_inputs extends BaseModel implements IGetPrice_inputs  {

    static CONTRACT_ADDRESS_FIELD_NAME = 'contractAddress';
    static DATA_FIELD_NAME = 'data';

    /** address: contract to query */
    contractAddress: string;
    /** bytes: the bytecode for the contract call */
    data: string;

    /**
     * constructor
     * @param values Can be used to set a webapi response or formValues to this newly constructed model
    * @useFormGroupValuesToModel if true use formValues
    */
    constructor(values?: Partial<IGetPrice_inputs>, useFormGroupValuesToModel = false) {
        super();

        if (values) {
            this.setValues(values, useFormGroupValuesToModel);
        }
    }

    /**
     * set the values.
     * @param values Can be used to set a webapi response to this newly constructed model
    */
    setValues(values: Partial<IGetPrice_inputs>, useFormGroupValuesToModel = false): void {
        if (values) {
            const rawValues = this.getValuesToUse(values, useFormGroupValuesToModel);
            this.contractAddress = this.getValue<string>(rawValues, GetPrice_inputs.CONTRACT_ADDRESS_FIELD_NAME);
            this.data = this.getValue<string>(rawValues, GetPrice_inputs.DATA_FIELD_NAME);
            // set values in model properties for added formControls
            super.setValuesInAddedPropertiesOfAttachedFormControls(values, useFormGroupValuesToModel);
        }
    }

    protected getFormGroup(): FormGroup {
        if (!this._formGroup) {
            this._formGroup = new FormGroup({
                contractAddress: new FormControl(this.contractAddress, [Validators.pattern('^(0x)?[a-fA-F0-9]{40}$'), ]),
                data: new FormControl(this.data, [Validators.pattern('^(0x)?[a-fA-F0-9]+$'), ]),
            });
        }
        return this._formGroup;
    }

    /**
     * set the FormGroup values to the model values.
    */
    setFormGroupValues() {
        this.$formGroup.controls[GetPrice_inputs.CONTRACT_ADDRESS_FIELD_NAME].setValue(this.contractAddress);
        this.$formGroup.controls[GetPrice_inputs.DATA_FIELD_NAME].setValue(this.data);
        // set formValues in added formControls
        super.setFormGroupValuesInAddedFormControls();
    }
}
